# Generated by Django 4.0.3 on 2022-03-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.ImageField(upload_to='course_photos')),
                ('middle', models.ImageField(upload_to='course_photos')),
                ('left', models.ImageField(upload_to='course_photos')),
            ],
            options={
                'verbose_name': 'Фото курсов лечения на главной странице',
                'verbose_name_plural': 'Фото курсов лечения на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Об Амбер Сакрум ',
                'verbose_name_plural': 'Об Амбер Сакрум',
            },
        ),
        migrations.CreateModel(
            name='MainPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='big_photos')),
                ('photo_2', models.ImageField(upload_to='big_photos')),
                ('photo_3', models.ImageField(upload_to='big_photos')),
            ],
            options={
                'verbose_name': 'Главные фото',
                'verbose_name_plural': 'Главные фото',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[(1, 'Комфорт'), (2, 'Стандарт')], default='1', max_length=1, verbose_name='Тип номера')),
                ('title', models.CharField(max_length=63, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_date', to='main_app.rooms')),
            ],
            options={
                'verbose_name': 'Занятая дата',
                'verbose_name_plural': 'Занятые даты',
            },
        ),
    ]
