# Generated by Django 4.0.3 on 2022-03-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCoursePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='main_course_photos')),
                ('photo_2', models.ImageField(upload_to='main_course_photos')),
                ('photo_3', models.ImageField(upload_to='main_course_photos')),
            ],
            options={
                'verbose_name': 'Фото для полного курса',
                'verbose_name_plural': 'Фото для полного курса',
            },
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'Комфорт'), ('2', 'Стандарт')], default='1', max_length=1, verbose_name='Тип номера'),
        ),
    ]
