# Generated by Django 4.0.3 on 2022-03-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maincoursephotos_alter_rooms_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='main_course_photos')),
                ('photo_2', models.ImageField(upload_to='main_course_photos')),
                ('photo_3', models.ImageField(upload_to='main_course_photos')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Описание полного курса',
                'verbose_name_plural': 'Описание для полного курса',
            },
        ),
        migrations.DeleteModel(
            name='MainCoursePhotos',
        ),
    ]
