# Generated by Django 4.0.3 on 2022-04-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_date', to='main_app.rooms'),
        ),
    ]
