# Generated by Django 4.0.3 on 2022-04-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_dates_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='date',
            field=models.CharField(blank=True, choices=[('1', 'Полный курс лечения'), ('2', 'День здоровья'), ('3', 'Посещение остеопата')], default='1', max_length=1, null=True, verbose_name='Занятая дата (для дня здоровя или посещения остеопата)'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заезда (только для полного курса лечения)'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда (только для полного курса лечения)'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_date', to='main_app.rooms', verbose_name='Тип комнаты (только для полного курса лечения)'),
        ),
    ]
