# Generated by Django 4.0.3 on 2022-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_dates_date_alter_dates_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='date',
        ),
        migrations.AddField(
            model_name='dates',
            name='course_date',
            field=models.DateField(blank=True, null=True, verbose_name='День лечения (только для дня здоровья или остеопата)'),
        ),
        migrations.AddField(
            model_name='dates',
            name='course_type',
            field=models.CharField(blank=True, choices=[('1', 'Полный курс лечения'), ('2', 'День здоровья'), ('3', 'Посещение остеопата')], default='1', max_length=1, null=True, verbose_name='Тип лечения'),
        ),
    ]
