# Generated by Django 4.0.3 on 2022-04-13 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_dates_date_dates_course_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luxe_room_full_health', models.FloatField(default=9300, verbose_name='Сутки полного курса лечения (номер "комфорт")')),
                ('standart_room_full_health', models.FloatField(default=8800, verbose_name='Сутки полного курса лечения (номер "стандарт")')),
                ('health_day', models.FloatField(default=6800, verbose_name='День здоровья')),
                ('osteopat', models.FloatField(default=5000, verbose_name='Посещение остеопата')),
            ],
            options={
                'verbose_name': 'Прайс лист',
                'verbose_name_plural': 'Прайс лист',
            },
        ),
        migrations.AlterField(
            model_name='dates',
            name='check_in',
            field=models.DateField(blank=True, help_text='Только для полного курса лечения', null=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='check_out',
            field=models.DateField(blank=True, help_text='Только для полного курса лечения', null=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='course_date',
            field=models.DateField(blank=True, help_text='Только для дня здоровья или остеопата', null=True, verbose_name='День лечения '),
        ),
        migrations.AlterField(
            model_name='dates',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Только для полного курса лечения', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_date', to='main_app.rooms', verbose_name='Тип комнаты'),
        ),
    ]
