# Generated by Django 4.0.3 on 2022-04-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
