# Generated by Django 4.0.3 on 2022-04-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField(max_length=250)),
            ],
            options={
                'verbose_name': 'Категория для туризма и досуга',
                'verbose_name_plural': 'Категории для туризма и досуга',
            },
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.categories')),
            ],
            options={
                'verbose_name': 'Запись для досуга и туризма',
                'verbose_name_plural': 'Записи для досуга и туризма',
            },
        ),
        migrations.CreateModel(
            name='TourismImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tourism_and_dosug')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourism_record', to='main_app.tourism')),
            ],
        ),
    ]
