# Generated by Django 4.0.3 on 2022-04-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_gallerycategory_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон на главной')),
            ],
            options={
                'verbose_name': 'Телефон на главной',
                'verbose_name_plural': 'Телефон на главной',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name': 'Категория для галерии', 'verbose_name_plural': 'Категории для галерии'},
        ),
    ]
