# Generated by Django 4.0.3 on 2022-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_mainphone_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя и фамилия')),
                ('image', models.ImageField(upload_to='staff', verbose_name='Фото')),
                ('level', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
            },
        ),
    ]
