# Generated by Django 4.0.3 on 2022-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luxe', models.ImageField(upload_to='numbers', verbose_name='Комфорт')),
                ('standart', models.ImageField(upload_to='numbers', verbose_name='Стандарт')),
            ],
            options={
                'verbose_name': 'Фото комнат',
                'verbose_name_plural': 'Фото комнат',
            },
        ),
    ]
