# Generated by Django 4.0.3 on 2023-01-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_numberimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayMiniDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='day_photos')),
                ('photo_2', models.ImageField(upload_to='day_photos')),
                ('photo_3', models.ImageField(upload_to='day_photos')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Описание дня здоровья мини',
                'verbose_name_plural': 'Описание дня здоровья мини',
            },
        ),
        migrations.AddField(
            model_name='prices',
            name='health_day_mini',
            field=models.IntegerField(default=2700, verbose_name='День здоровья "мини"'),
        ),
    ]
