# Generated by Django 4.0.3 on 2023-01-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_coursesphoto_day_mini'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesphoto',
            old_name='left',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='coursesphoto',
            old_name='middle',
            new_name='full_course',
        ),
        migrations.RenameField(
            model_name='coursesphoto',
            old_name='right',
            new_name='osteopat',
        ),
    ]
