# Generated by Django 4.0.3 on 2023-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourseMini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(upload_to='main_course_photos')),
                ('photo_2', models.ImageField(upload_to='main_course_photos')),
                ('photo_3', models.ImageField(upload_to='main_course_photos')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Описание полного курса МИНИ',
                'verbose_name_plural': 'Описание для полного курса МИНИ',
            },
        ),
        migrations.AlterModelOptions(
            name='maincourse',
            options={'verbose_name': 'Описание полного курса МАКСИ', 'verbose_name_plural': 'Описание для полного курса МАКСИ'},
        ),
    ]
