# Generated by Django 4.0.3 on 2023-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_maincoursemini_alter_maincourse_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='luxe_room_full_health',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='standart_room_full_health',
        ),
        migrations.AddField(
            model_name='prices',
            name='full_health_maxi',
            field=models.IntegerField(default=8800, verbose_name='Сутки полного курса лечения МАКСИ'),
        ),
        migrations.AddField(
            model_name='prices',
            name='full_health_mini',
            field=models.IntegerField(default=8800, verbose_name='Сутки полного курса лечения МИНИ'),
        ),
    ]
