# Generated by Django 4.0.3 on 2023-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_remove_prices_luxe_room_full_health_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesphoto',
            old_name='full_course',
            new_name='full_course_maxi',
        ),
        migrations.AddField(
            model_name='coursesphoto',
            name='full_course_mini',
            field=models.ImageField(null=True, upload_to='course_photos'),
        ),
    ]
