# Generated by Django 4.0.3 on 2023-04-14 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_rename_full_course_coursesphoto_full_course_maxi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название процедуры')),
                ('description', models.TextField(verbose_name='Описание процедуры')),
                ('photo_1', models.ImageField(upload_to='procedures')),
                ('photo_2', models.ImageField(upload_to='procedures')),
                ('photo_3', models.ImageField(upload_to='procedures')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Процедуры',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.AddField(
            model_name='rooms',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='rooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена за сутки'),
            preserve_default=False,
        ),
    ]
