# Generated by Django 4.0.3 on 2023-04-16 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_procedures_rooms_description_rooms_photo_rooms_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='photo',
            new_name='photo_1',
        ),
        migrations.AddField(
            model_name='rooms',
            name='photo_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='rooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='photo_3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='rooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='photo_4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='rooms'),
            preserve_default=False,
        ),
    ]
