# Generated by Django 4.0.3 on 2023-04-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_rename_photo_rooms_photo_1_rooms_photo_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название спецпредложения')),
                ('description', models.TextField(verbose_name='Описание спецпредложения')),
                ('photo', models.ImageField(upload_to='procedures')),
            ],
            options={
                'verbose_name': 'Спецпредложение',
                'verbose_name_plural': 'Спецпредложения',
            },
        ),
    ]
