# Generated by Django 4.0.3 on 2023-04-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
