# Generated by Django 4.0.3 on 2023-05-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='daydescription',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='daydescription',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='daydescription',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='daydescription',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='daydescription',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='daydescription',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='dayminidescription',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='dayminidescription',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='dayminidescription',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='dayminidescription',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='dayminidescription',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='dayminidescription',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincourse',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincoursemini',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincoursemini',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincoursemini',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincoursemini',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincoursemini',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='maincoursemini',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='osteopatdescription',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='osteopatdescription',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='osteopatdescription',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='osteopatdescription',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='osteopatdescription',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
        migrations.AddField(
            model_name='osteopatdescription',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='main_course_photos'),
        ),
    ]
