# Generated by Django 4.0.3 on 2023-05-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_daydescription_photo_4_daydescription_photo_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
        migrations.AddField(
            model_name='offer',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='procedures'),
        ),
    ]
