# Generated by Django 4.0.3 on 2023-05-29 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_offer_photo_1_offer_photo_2_offer_photo_3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запись для досуга и туризма',
                'verbose_name_plural': 'Записи для досуга и туризма',
            },
        ),
        migrations.CreateModel(
            name='SmiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='smi')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smi_record', to='main_app.smi')),
            ],
        ),
    ]
