# Generated by Django 4.0.3 on 2023-07-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_smi_smiimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smi',
            options={'verbose_name': 'СМИ', 'verbose_name_plural': 'СМИ'},
        ),
    ]
