# Generated by Django 4.0.3 on 2022-04-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0011_delete_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(blank=True, choices=[('1', 'Полный курс лечения'), ('2', 'День здоровья'), ('3', 'Посещение остеопата')], default='1', max_length=1, null=True, verbose_name='Тип лечения')),
                ('course_date', models.DateField(blank=True, help_text='Только для дня здоровья или остеопата', null=True, verbose_name='День лечения ')),
                ('check_in', models.DateField(blank=True, help_text='Только для полного курса лечения', null=True, verbose_name='Дата заезда')),
                ('check_out', models.DateField(blank=True, help_text='Только для полного курса лечения', null=True, verbose_name='Дата выезда')),
                ('room', models.ForeignKey(blank=True, help_text='Только для полного курса лечения', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_date', to='main_app.rooms', verbose_name='Тип комнаты')),
            ],
            options={
                'verbose_name': 'Занятая дата',
                'verbose_name_plural': 'Занятые даты',
            },
        ),
    ]
