# Generated by Django 4.0.3 on 2022-04-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка для полного курса лечения', 'verbose_name_plural': 'Заявки для полного курса лечения'},
        ),
    ]
