# Generated by Django 4.0.3 on 2022-04-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата приема')),
                ('clients_info', models.TextField(verbose_name='Информация о пациенте')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.IntegerField(verbose_name='Итоговая стоимость приема (в рублях)')),
                ('status', models.CharField(choices=[('1', 'Оплачено'), ('2', 'Ожидает звонка администратора'), ('3', 'Процесс оплаты'), ('4', 'Отказано')], default='2', max_length=40, verbose_name='Статус')),
                ('date_in_process_pay', models.DateField(blank=True, null=True, verbose_name='Дата перевода в процесс оплаты')),
                ('pay_day', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'Заявка для дня здоровья',
                'verbose_name_plural': 'Заявки для дня здоровья',
            },
        ),
        migrations.CreateModel(
            name='OrderOsteopat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Дата приема')),
                ('clients_info', models.TextField(verbose_name='Информация о пациенте')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('price', models.IntegerField(verbose_name='Итоговая стоимость приема (в рублях)')),
                ('status', models.CharField(choices=[('1', 'Оплачено'), ('2', 'Ожидает звонка администратора'), ('3', 'Процесс оплаты'), ('4', 'Отказано')], default='2', max_length=40, verbose_name='Статус')),
                ('date_in_process_pay', models.DateField(blank=True, null=True, verbose_name='Дата перевода в процесс оплаты')),
                ('pay_day', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'Заявка для приема остеопата',
                'verbose_name_plural': 'Заявки для приема остеопата',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='date_in_process_pay',
            field=models.DateField(blank=True, null=True, verbose_name='Дата перевода в процесс оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Оплачено'), ('2', 'Ожидает звонка администратора'), ('3', 'Процесс оплаты'), ('4', 'Отказано')], default='2', max_length=40, verbose_name='Статус'),
        ),
    ]
