# Generated by Django 4.0.3 on 2023-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderday_orderosteopat_order_date_in_process_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderday',
            name='price',
        ),
        migrations.AddField(
            model_name='orderday',
            name='typeof',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип дня (мини или макси)'),
        ),
    ]
