# Generated by Django 4.0.3 on 2023-04-21 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_offer_price'),
        ('orders', '0006_remove_orderday_price_orderday_typeof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.rooms', verbose_name='Назначенный системой номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Выбранный тип номера'),
        ),
    ]
